/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.15
 * Contact: nurmi@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
import (
	"time"
)
// AnalysisArchiveTransitionHistory A rule for auto-archiving image analysis by time and/or tag-history
type AnalysisArchiveTransitionHistory struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	ImageDigest string `json:"imageDigest,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	RuleId string `json:"rule_id,omitempty"`
	Transition string `json:"transition,omitempty"`
	// The task that created & updated this entry
	TransitionTaskId string `json:"transition_task_id,omitempty"`
}
