/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.15
 * Contact: nurmi@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
// Whitelist A collection of whitelist items to match a policy evaluation against.
type Whitelist struct {
	Comment string `json:"comment,omitempty"`
	Id string `json:"id"`
	Items []WhitelistItem `json:"items,omitempty"`
	Name string `json:"name,omitempty"`
	Version string `json:"version"`
}
