/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.15
 * Contact: nurmi@anchore.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client
import (
	"time"
)
// EventResponseEvent struct for EventResponseEvent
type EventResponseEvent struct {
	Category string `json:"category,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
	Level string `json:"level,omitempty"`
	Message string `json:"message,omitempty"`
	Resource EventResponseEventResource `json:"resource,omitempty"`
	Source EventResponseEventSource `json:"source,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	Type string `json:"type,omitempty"`
}
